version: '3.7'
services:
  readarr:
    image: hotio/readarr:pr-a3c03c5
    container_name: readarr
    hostname: readarr
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
      - ../Data/books:/books
      - ../Data/audiobooks:/audiobooks
      - ../Data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.readarr.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.readarr.entrypoints=web-secure"
      - "traefik.http.routers.readarr.service=readarr"
      - "traefik.http.routers.readarr.tls=true"
      - "traefik.http.services.readarr.loadbalancer.server.port=8787" # Proxied Port
